In [1]:
# IMPORT DEPENDENCIES
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import requests
import sqlite3
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# Some questions from the data

In [2]:
# 1. GET Population vs YR Data
# 2. are places with highest vaccination rate also places with least cases or deaths
# 3. what were the first and last countries to become polio free (have greater than 95% vac percentage) 
# at what point did half the world become polio free

# Percentage polio immuniziation coverage amongst 1 yr olds in different countries from 1980 to 2017

In [3]:
# The dataset seen below is the percentage polio immuniziation coverage amongst 1 yr
# olds in different countries from 1980 to 2017
one_yr_olds=pd.read_csv("/Users/muhammadwaliji/Desktop/personal_projects/polio_data/data.csv",header=[1])
one_yr_olds=one_yr_olds.set_index("Country")
# one_yr_olds=one_yr_olds.set_index("Country")
one_yr_olds.head(1)

,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,...,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,60,60,60,58,62,67,68,66,63,64,...,33,35,25,11,15,16,5,5,3,NaN

In [4]:
# # This is a way to get the value of every country for a these years (years are column headers)
c = one_yr_olds.loc[:,("1989","1990")]

# this is the way to get the specific value of all column for a row
s = one_yr_olds.loc[("Switzerland","Afghanistan"),:]

In [5]:
# Converting the table from wide form to long form
one_yr_olds_long=one_yr_olds.unstack().reset_index().rename(columns={'level_0': 'year', 0: 'perc_coverage'})

# fill na values with 0
one_yr_olds_long.fillna(0)
one_yr_olds_long.head(1)

   year      Country perc_coverage
0  2017  Afghanistan            60

In [6]:
# # Option 2: don't worry about pandas, and just write it using a for loop.
# years = one_yr_olds.columns[1:].tolist()
# countries = one_yr_olds['Country'].tolist()
# output_list = []
# for year in years:
#     for i in range(len(countries)):
#         country = countries[i]
#         output_list.append({
#             'country': country,
#             'year': year,
#             'instances': one_yr_olds[year][i],
#         })
# output_df = pd.DataFrame.from_records(output_list)
# output_df.head()

# Longitude and latitude of all countries

In [12]:
long_lat=pd.read_html("https://developers.google.com/public-data/docs/canonical/countries_csv",skiprows=1)[0]

long_lat.columns=["country_code","latitude","longitude","name"]

# Continent and country table

In [13]:
continent=pd.read_csv("/Users/muhammadwaliji/Desktop/personal_projects/polio_data/continent_country.csv")

# Population data for the world

In [14]:
population_data=pd.read_html("http://www.worldometers.info/world-population/population-by-country/")[0]
population_data=population_data.drop(columns=['#'])
population_data.columns=["country","population","yearly_change","net_change","density_p/km2","area_in_km2","migrants","fert_rate","median_age","urban_pop_perc","world_share"]

# Extracting Disease Data using API

In [15]:
url = "http://apps.who.int/gho/athena/data/GHO/"
url_after = "?format=html&filter=COUNTRY:*"
polio_code = "poliov"

In [16]:
polio_url = url + polio_code + url_after
polio_raw = pd.read_html(polio_url)[0]
# polio_raw = polio_raw.set_index("COUNTRY")

In [17]:
polio_raw.loc[lambda df:df.SEX == 'Male']
polio_raw.loc[lambda df:df.RESIDENCEAREATYPE == 'Urban'].set_index("COUNTRY").sort_values(by=['YEAR'])

,GHO,DATASOURCE,PUBLISHSTATE,YEAR,REGION,EDUCATIONLEVEL,SEX,RESIDENCEAREATYPE,WEALTHQUINTILE,DHSMICSGEOREGION,DISPLAY VALUE,NUMERIC VALUE,LOW RANGE,HIGH RANGE,Comment
COUNTRY,,,,,,,,,,,,,,,
Belize,Polio immunization coverage among one-year-old...,RHS,Published,1991,Americas,NaN,NaN,Urban,NaN,NaN,81.1 [73.9-86.8],81.14478,73.87375,86.75506,NaN
Honduras,Polio immunization coverage among one-year-old...,RHS,Published,1991,Americas,NaN,NaN,Urban,NaN,NaN,83.5 [80.1-86.5],83.53658,80.08575,86.49032,NaN
Costa Rica,Polio immunization coverage among one-year-old...,RHS,Published,1992,Americas,NaN,NaN,Urban,NaN,NaN,86.7 [80.7-91.0],86.66666,80.67541,91.00748,NaN
Nicaragua,Polio immunization coverage among one-year-old...,RHS,Published,1992,Americas,NaN,NaN,Urban,NaN,NaN,89.9 [86.4-92.6],89.91454,86.44275,92.57364,NaN
Turkey,Polio immunization coverage among one-year-old...,DHS,Published,1993,Europe,NaN,NaN,Urban,NaN,NaN,85.9 [80.3-90.1],85.88501,80.34871,90.05463,NaN
El Salvador,Polio immunization coverage among one-year-old...,RHS,Published,1993,Americas,NaN,NaN,Urban,NaN,NaN,82.1 [74.3-87.9],82.08092,74.29402,87.89339,NaN
Kenya,Polio immunization coverage among one-year-old...,DHS,Published,1993,Africa,NaN,NaN,Urban,NaN,NaN,93.4 [88.1-96.4],93.38621,88.14047,96.40624,NaN
Ghana,Polio immunization coverage among one-year-old...,DHS,Published,1993,Africa,NaN,NaN,Urban,NaN,NaN,79.2 [72.0-84.9],79.18781,71.96375,84.94001,NaN
Philippines,Polio immunization coverage among one-year-old...,DHS,Published,1993,Western Pacific,NaN,NaN,Urban,NaN,NaN,81.2 [78.0-83.9],81.15643,78.03599,83.92488,NaN
Bangladesh,Polio immunization coverage among one-year-old...,DHS,Published,1993,South-East Asia,NaN,NaN,Urban,NaN,NaN,79.3 [70.8-85.8],79.28562,70.77499,85.81461,NaN
Zimbabwe,Polio immunization coverage among one-year-old...,DHS,Published,1994,Africa,NaN,NaN,Urban,NaN,NaN,89.6 [83.9-93.5],89.64136,83.93504,93.47826,NaN
Bolivia (Plurinational State of),Polio immunization coverage among one-year-old...,DHS,Published,1994,Americas,NaN,NaN,Urban,NaN,NaN,55.5 [51.3-59.6],55.49081,51.27625,59.62785,NaN
CÃƒÂ´te d'Ivoire,Polio immunization coverage among one-year-old...,DHS,Published,1994,Africa,NaN,NaN,Urban,NaN,NaN,71.3 [67.4-74.9],71.31773,67.44984,74.89706,NaN
Indonesia,Polio immunization coverage among one-year-old...,DHS,Published,1994,South-East Asia,NaN,NaN,Urban,NaN,NaN,78.0 [72.5-82.6],77.97865,72.48643,82.63713,NaN
Central African Republic,Polio immunization coverage among one-year-old...,DHS,Published,1994,Africa,NaN,NaN,Urban,NaN,NaN,65.7 [60.3-70.7],65.67773,60.29852,70.68248,NaN
Ecuador,Polio immunization coverage among one-year-old...,RHS,Published,1994,Americas,NaN,NaN,Urban,NaN,NaN,81.0 [75.4-85.6],81.03147,75.38869,85.62716,NaN
Haiti,Polio immunization coverage among one-year-old...,DHS,Published,1994,Americas,NaN,NaN,Urban,NaN,NaN,50.7 [44.8-56.6],50.72240,44.81829,56.60643,NaN
Paraguay,Polio immunization coverage among one-year-old...,RHS,Published,1995,Americas,NaN,NaN,Urban,NaN,NaN,No data,NaN,NaN,NaN,Not available.
Mali,Polio immunization coverage among one-year-old...,DHS,Published,1995,Africa,NaN,NaN,Urban,NaN,NaN,65.2 [58.8-71.2],65.24932,58.78105,71.19987,NaN
Guatemala,Polio immunization coverage among one-year-old...,DHS,Published,1995,Americas,NaN,NaN,Urban,NaN,NaN,50.9 [43.7-58.0],50.89091,43.71002,58.03524,NaN
Colombia,Polio immunization coverage among one-year-old...,DHS,Published,1995,Americas,NaN,NaN,Urban,NaN,NaN,79.7 [76.6-82.5],79.69199,76.61864,82.45388,NaN
Egypt,Polio immunization coverage among one-year-old...,DHS,Published,1995,Eastern Mediterranean,NaN,NaN,Urban,NaN,NaN,90.4 [86.9-92.9],90.35700,86.94935,92.94706,NaN
Kazakhstan,Polio immunization coverage among one-year-old...,DHS,Published,1995,Europe,NaN,NaN,Urban,NaN,NaN,55.4 [42.2-67.9],55.40940,42.15181,67.93959,NaN
Uganda,Polio immunization coverage among one-year-old...,DHS,Published,1995,Africa,NaN,NaN,Urban,NaN,NaN,67.5 [62.1-72.5],67.50027,62.10206,72.47042,NaN
Comoros,Polio immunization coverage among one-year-old...,DHS,Published,1996,Africa,NaN,NaN,Urban,NaN,NaN,65.2 [56.4-73.1],65.21739,56.42374,73.08305,NaN
Brazil,Polio immunization coverage among one-year-old...,DHS,Published,1996,Americas,NaN,NaN,Urban,NaN,NaN,84.5 [81.1-87.4],84.50243,81.07931,87.40247,NaN
Uzbekistan,Polio immunization coverage among one-year-old...,DHS,Published,1996,Europe,NaN,NaN,Urban,NaN,NaN,87.5 [80.3-92.4],87.54639,80.27123,92.39302,NaN
Nepal,Polio immunization coverage among one-year-old...,DHS,Published,1996,South-East Asia,NaN,NaN,Urban,NaN,NaN,77.4 [66.3-85.6],77.37248,66.27306,85.61214,NaN
Benin,Polio immunization coverage among one-year-old...,DHS,Published,1996,Africa,NaN,NaN,Urban,NaN,NaN,67.6 [59.1-75.1],67.62024,59.06115,75.14301,NaN
Dominican Republic,Polio immunization coverage among one-year-old...,DHS,Published,1996,Americas,NaN,NaN,Urban,NaN,NaN,53.9 [47.4-60.3],53.88771,47.35614,60.28846,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Senegal,Polio immunization coverage among one-year-old...,DHS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,84.2 [78.9-88.5],84.24013,78.85939,88.45190,NaN
Eswatini,Polio immunization coverage among one-year-old...,MICS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,88.1 [76.4-94.4],88.10545,76.43315,94.41879,NaN
Kenya,Polio immunization coverage among one-year-old...,DHS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,79.0 [74.7-82.7],79.00582,74.74459,82.71435,NaN
Cameroon,Polio immunization coverage among one-year-old...,MICS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,92.8 [90.2-94.7],92.76784,90.21540,94.69360,NaN
Egypt,Polio immunization coverage among one-year-old...,DHS,Published,2014,Eastern Mediterranean,NaN,NaN,Urban,NaN,NaN,96.8 [95.1-97.9],96.81339,95.09016,97.94488,NaN
Nepal,Polio immunization coverage among one-year-old...,MICS,Published,2014,South-East Asia,NaN,NaN,Urban,NaN,NaN,97.9 [93.1-99.4],97.87199,93.06375,99.36971,NaN
Cuba,Polio immunization coverage among one-year-old...,MICS,Published,2014,Americas,NaN,NaN,Urban,NaN,NaN,63.5 [54.2-71.8],63.47234,54.19174,71.84943,NaN
Chad,Polio immunization coverage among one-year-old...,DHS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,53.4 [48.2-58.6],53.43040,48.20954,58.57716,NaN
Guinea-Bissau,Polio immunization coverage among one-year-old...,MICS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,80.0 [75.3-84.1],80.04147,75.26176,84.09287,NaN
Sudan,Polio immunization coverage among one-year-old...,MICS,Published,2014,Eastern Mediterranean,NaN,NaN,Urban,NaN,NaN,84.0 [80.1-87.3],84.02739,80.05299,87.33517,NaN
Zimbabwe,Polio immunization coverage among one-year-old...,MICS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,93.0 [90.5-94.9],92.98618,90.49602,94.86093,NaN
Guatemala,Polio immunization coverage among one-year-old...,DHS,Published,2014,Americas,NaN,NaN,Urban,NaN,NaN,83.8 [79.4-87.3],83.77363,79.42963,87.34642,NaN
Ghana,Polio immunization coverage among one-year-old...,DHS,Published,2014,Africa,NaN,NaN,Urban,NaN,NaN,83.7 [79.0-87.6],83.70616,78.95792,87.55186,NaN
Dominican Republic,Polio immunization coverage among one-year-old...,MICS,Published,2014,Americas,NaN,NaN,Urban,NaN,NaN,68.8 [66.0-71.5],68.83974,66.03419,71.51352,NaN
Bangladesh,Polio immunization coverage among one-year-old...,DHS,Published,2014,South-East Asia,NaN,NaN,Urban,NaN,NaN,93.0 [89.5-95.4],93.02454,89.54348,95.40618,NaN
Cambodia,Polio immunization coverage among one-year-old...,DHS,Published,2014,Western Pacific,NaN,NaN,Urban,NaN,NaN,90.0 [86.1-92.9],90.03218,86.11326,92.93587,NaN
El Salvador,Polio immunization coverage among one-year-old...,MICS,Published,2014,Americas,NaN,NaN,Urban,NaN,NaN,90.5 [86.3-93.6],90.54872,86.30035,93.57767,NaN
Serbia,Polio immunization coverage among one-year-old...,MICS,Published,2014,Europe,NaN,NaN,Urban,NaN,NaN,88.7 [82.3-92.9],88.65018,82.25282,92.93942,NaN
Kyrgyzstan,Polio immunization coverage among one-year-old...,MICS,Published,2014,Europe,NaN,NaN,Urban,NaN,NaN,85.0 [79.8-89.1],85.04903,79.80540,89.11681,NaN
Senegal,Polio immunization coverage among one-year-old...,DHS,Published,2015,Africa,NaN,NaN,Urban,NaN,NaN,82.5 [73.6-88.9],82.51199,73.56441,88.88853,NaN
Myanmar,Polio immunization coverage among one-year-old...,DHS,Published,2015,South-East Asia,NaN,NaN,Urban,NaN,NaN,76.0 [68.3-82.4],76.03789,68.33321,82.35212,NaN
Mexico,Polio immunization coverage among one-year-old...,MICS,Published,2015,Americas,NaN,NaN,Urban,NaN,NaN,69.9 [64.6-74.7],69.89941,64.58284,74.73017,NaN
Malawi,Polio immunization coverage among one-year-old...,DHS,Published,2015,Africa,NaN,NaN,Urban,NaN,NaN,76.5 [69.7-82.1],76.46304,69.71577,82.09315,NaN
United Republic of Tanzania,Polio immunization coverage among one-year-old...,DHS,Published,2015,Africa,NaN,NaN,Urban,NaN,NaN,86.6 [83.6-89.1],86.58056,83.59373,89.09456,NaN
Angola,Polio immunization coverage among one-year-old...,DHS,Published,2015,Africa,NaN,NaN,Urban,NaN,NaN,51.8 [47.8-55.7],51.78427,47.82862,55.71768,NaN
Afghanistan,Polio immunization coverage among one-year-old...,DHS,Published,2015,Eastern Mediterranean,NaN,NaN,Urban,NaN,NaN,69.8 [64.7-74.5],69.78782,64.67236,74.45513,NaN
Colombia,Polio immunization coverage among one-year-old...,DHS,Published,2015,Americas,NaN,NaN,Urban,NaN,NaN,No data,NaN,NaN,NaN,Not available.
Turkmenistan,Polio immunization coverage among one-year-old...,MICS,Published,2015,Europe,NaN,NaN,Urban,NaN,NaN,97.0 [94.1-98.5],97.02347,94.11951,98.51598,NaN
Zimbabwe,Polio immunization coverage among one-year-old...,DHS,Published,2015,Africa,NaN,NaN,Urban,NaN,NaN,87.9 [83.3-91.3],87.86904,83.30273,91.31675,NaN
Kazakhstan,Polio immunization coverage among one-year-old...,MICS,Published,2015,Europe,NaN,NaN,Urban,NaN,NaN,88.7 [84.8-91.7],88.67793,84.76134,91.68662,NaN

In [18]:
# A little bit of a background on the data. Each country is supposed to have 12 different attributes because of which 
# for each year each country will have 12 different numeric values, however this is not the case. Some countries have
# some values but not others.

In [19]:
# polio_raw.loc[lambda df: np.logical_and(df.YEAR == 1991, df.COUNTRY == 'Belize')]

In [20]:
pol_cols = polio_raw.loc[:, ['GHO','YEAR', 'COUNTRY','NUMERIC VALUE']].copy('deep')
pol_cols['DISEASE'] = 'Polio'

In [21]:
pol_cols.count()

GHO              7475
YEAR             7475
COUNTRY          7475
NUMERIC VALUE    6766
DISEASE          7475
dtype: int64

In [22]:
pol_cols["NUMERIC VALUE"]=pol_cols["NUMERIC VALUE"].fillna(0)

In [23]:
pol_cols.head()

,GHO,YEAR,COUNTRY,NUMERIC VALUE,DISEASE
0,Polio immunization coverage among one-year-old...,1999,Dominican Republic,53.30638,Polio
1,Polio immunization coverage among one-year-old...,2005,Armenia,75.64944,Polio
2,Polio immunization coverage among one-year-old...,2006,Benin,60.80764,Polio
3,Polio immunization coverage among one-year-old...,2006,Burkina Faso,76.26176,Polio
4,Polio immunization coverage among one-year-old...,2007,Bangladesh,90.46639,Polio

In [24]:
# Not sure if this is useful because it looks like there is some discrepiency in country data vs year data
# for example the year 1991 has a lot of numbers for the same year
pol_cols.sort_values(by=['YEAR'])

,GHO,YEAR,COUNTRY,NUMERIC VALUE,DISEASE
5686,Polio immunization coverage among one-year-old...,1991,Honduras,76.38889,Polio
4371,Polio immunization coverage among one-year-old...,1991,Belize,84.11552,Polio
1342,Polio immunization coverage among one-year-old...,1991,Belize,86.33093,Polio
6690,Polio immunization coverage among one-year-old...,1991,Honduras,78.93082,Polio
2098,Polio immunization coverage among one-year-old...,1991,Belize,80.91603,Polio
5768,Polio immunization coverage among one-year-old...,1991,Honduras,88.88889,Polio
156,Polio immunization coverage among one-year-old...,1991,Honduras,82.30453,Polio
2117,Polio immunization coverage among one-year-old...,1991,Honduras,84.85607,Polio
6779,Polio immunization coverage among one-year-old...,1991,Honduras,84.56376,Polio
6662,Polio immunization coverage among one-year-old...,1991,Belize,83.92857,Polio
5739,Polio immunization coverage among one-year-old...,1991,Belize,75.00000,Polio
5673,Polio immunization coverage among one-year-old...,1991,Belize,83.55437,Polio
2927,Polio immunization coverage among one-year-old...,1991,Honduras,81.75676,Polio
3342,Polio immunization coverage among one-year-old...,1991,Honduras,83.78378,Polio
3341,Polio immunization coverage among one-year-old...,1991,Honduras,87.61062,Polio
2170,Polio immunization coverage among one-year-old...,1991,Belize,84.44444,Polio
722,Polio immunization coverage among one-year-old...,1991,Honduras,85.90604,Polio
3833,Polio immunization coverage among one-year-old...,1991,Belize,0.00000,Polio
416,Polio immunization coverage among one-year-old...,1991,Honduras,83.53658,Polio
5687,Polio immunization coverage among one-year-old...,1991,Honduras,86.99552,Polio
4721,Polio immunization coverage among one-year-old...,1991,Honduras,85.09804,Polio
4370,Polio immunization coverage among one-year-old...,1991,Belize,82.03125,Polio
3504,Polio immunization coverage among one-year-old...,1991,Honduras,86.53847,Polio
4146,Polio immunization coverage among one-year-old...,1991,Honduras,77.77778,Polio
7456,Polio immunization coverage among one-year-old...,1991,Honduras,89.33333,Polio
2969,Polio immunization coverage among one-year-old...,1991,Honduras,83.91421,Polio
2954,Polio immunization coverage among one-year-old...,1991,Belize,81.14478,Polio
2953,Polio immunization coverage among one-year-old...,1991,Belize,85.59322,Polio
243,Polio immunization coverage among one-year-old...,1991,Honduras,82.91536,Polio
4145,Polio immunization coverage among one-year-old...,1991,Honduras,80.99173,Polio
...,...,...,...,...,...
6792,Polio immunization coverage among one-year-old...,2015,Malawi,81.14824,Polio
2932,Polio immunization coverage among one-year-old...,2015,Kazakhstan,97.24435,Polio
4132,Polio immunization coverage among one-year-old...,2015,Afghanistan,82.38725,Polio
4133,Polio immunization coverage among one-year-old...,2015,Afghanistan,80.41135,Polio
4096,Polio immunization coverage among one-year-old...,2015,Senegal,76.87288,Polio
4095,Polio immunization coverage among one-year-old...,2015,Senegal,84.12270,Polio
4090,Polio immunization coverage among one-year-old...,2015,Senegal,72.95664,Polio
6764,Polio immunization coverage among one-year-old...,2015,Zimbabwe,86.99223,Polio
4984,Polio immunization coverage among one-year-old...,2015,United Republic of Tanzania,88.33532,Polio
6278,Polio immunization coverage among one-year-old...,2015,Angola,11.94667,Polio
6277,Polio immunization coverage among one-year-old...,2015,Afghanistan,46.76425,Polio
4976,Polio immunization coverage among one-year-old...,2015,Turkmenistan,92.71822,Polio
3040,Polio immunization coverage among one-year-old...,2015,United Republic of Tanzania,85.22553,Polio
3038,Polio immunization coverage among one-year-old...,2015,Turkmenistan,0.00000,Polio
2046,Polio immunization coverage among one-year-old...,2015,Angola,51.78427,Polio
4009,Polio immunization coverage among one-year-old...,2015,Turkmenistan,99.41351,Polio
1273,Polio immunization coverage among one-year-old...,2015,Angola,39.94756,Polio
6279,Polio immunization coverage among one-year-old...,2015,Angola,39.46497,Polio
6253,Polio immunization coverage among one-year-old...,2015,United Republic of Tanzania,84.96096,Polio
6752,Polio immunization coverage among one-year-old...,2015,United Republic of Tanzania,84.01569,Polio
1039,Polio immunization coverage among one-year-old...,2015,Angola,42.98235,Polio
267,Polio immunization coverage among one-year-old...,2015,United Republic of Tanzania,84.65677,Polio
7180,Polio immunization coverage among one-year-old...,2015,Kazakhstan,86.70039,Polio
4898,Polio immunization coverage among one-year-old...,2015,Kazakhstan,86.33241,Polio
2089,Polio immunization coverage among one-year-old...,2015,Turkmenistan,97.02347,Polio
2090,Polio immunization coverage among one-year-old...,2015,United Republic of Tanzania,86.58056,Polio
2998,Polio immunization coverage among one-year-old...,2015,Colombia,0.00000,Polio
4897,Polio immunization coverage among one-year-old...,2015,Kazakhstan,81.89660,Polio
6749,Polio immunization coverage among one-year-old...,2015,Turkmenistan,100.00000,Polio
4518,Polio immunization coverage among one-year-old...,2015,Senegal,90.63467,Polio

##### Another way to easily query from this database is by converting dataframe in SQL and performing queries in Pandas
#### You can either convert to SQLITE and run as a file on the computer or put it in mySQL

# Adding a Pandas Dataframe and adding it to SQLITE

In [25]:
# Step 1: Set up the location where you want the sqlite file you make to be. This can be the 
# same folder where the data exists or some other location

sqlite_filename = '/Users/muhammadwaliji/Desktop/personal_projects/polio_data/data_table.sqlite'

In [26]:
# Step 2: Create a connection with the SQLite file you created 
# NOTE: SQLITE is essentially a database which means that it can hold various tables inside it

conn = sqlite3.connect(sqlite_filename)

In [27]:
# Step 3: Add the DATAFRAME you made above into the SQLite using the .to_sql command
# Make sure that the thing you write before the ".to_sql" is the name of the dataframe
# and makesure to add the connection and if exists to this. Also here is you chance to specify
# what you want to name the table. I called my table "pvac_perc_1yrolds"

#  AT THIS POINT YOU HAVE ADDED THE DATAFRAME YOU MADE ABOVE INTO THE SQLITE FILE
# YOU CAN NOW EITHER CONTINUE TO ADD MORE TABLES OR QUERY THE CURRENT TABLE

# one_yr_olds_long.to_sql("pvac_perc_1yrolds",conn,if_exists="replace",index=False)

In [28]:
# STEP 4: this is how to query the table.
# YOU DONT HAVE TO ASSIGN A VARIABLE TO IT BUT IF YOU DO ITS JUST EASIER TO CALL IT LATER

df_from_sqlite = pd.read_sql_query("""
SELECT * FROM pvac_perc_1yrolds
LIMIT 5
""", conn)

df_from_sqlite

   year      Country perc_coverage
0  2017  Afghanistan            60
1  2017      Albania            99
2  2017      Algeria            91
3  2017      Andorra            99
4  2017       Angola            47

In [29]:
# Adding one_yr_olds_long to sqlite file
one_yr_olds_long.to_sql("pvac_perc_1yrolds",conn,if_exists="replace",index=False)

# Adding pol_cols to sqlite file
pol_cols.to_sql("polio_instances", conn, if_exists="replace")

# Adding Population data from the country to sqlite file
population_data.to_sql("population",conn,if_exists="replace")

# Adding continent_country data to sqlite file
continent.to_sql("continent_country",conn,if_exists="replace")

# ADDING long_lat to sqlite file
long_lat.to_sql("country_coords", conn, if_exists="replace")

/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2130: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype)

In [30]:

continent_population_added=pd.read_sql_query("""
SELECT cc.country_code, cc.name, continent_country.Continent,cc.latitude, cc.longitude, population.population,population.world_share
FROM country_coords AS cc
JOIN continent_country ON continent_country.Country = cc.name
JOIN population ON continent_country.Country = population.country
;
""", conn)

continent_population_added.head()

,country_code,name,Continent,latitude,longitude,population,world_share
0,AD,Andorra,Europe,42.546245,1.601554,77072,0.00 %
1,AE,United Arab Emirates,Asia,23.424076,53.847818,9682088,0.13 %
2,AF,Afghanistan,Asia,33.939110,67.709953,37209007,0.48 %
3,AG,Antigua and Barbuda,North America,17.060816,-61.796428,104084,0.00 %
4,AL,Albania,Europe,41.153332,20.168331,2938428,0.04 %

In [31]:
country_coverage_info = pd.read_sql_query("""

SELECT cc.country_code, cc.name, continent_country.Continent,cc.latitude, 
cc.longitude, population.population,population.world_share, pvac_perc_1yrolds.perc_coverage,
pvac_perc_1yrolds.year

FROM country_coords AS cc

JOIN continent_country ON continent_country.Country = cc.name
JOIN population ON continent_country.Country = population.country
JOIN pvac_perc_1yrolds ON pvac_perc_1yrolds.Country =cc.name
;
""", conn)

In [32]:
# renaming columns so all start with lower case and dont have any spaces in the name
country_coverage_info.columns=["country_code","name","continent","latitude","longitude","population","perc_pop_world_share","perc_coverage","year"]

#Taking the % sign out of the 'perc_pop_world_share' column so that its easy to convert to int later
country_coverage_info.loc[:,"perc_pop_world_share"]=country_coverage_info["perc_pop_world_share"].str.replace(" %","")

# REPACING NONE IN PERC_COVERAGE COL WITH 0
country_coverage_info.replace(to_replace=[None], value=0, inplace=True)

# Looking at the column head to see if all the changes worked
country_coverage_info.head()

,country_code,name,continent,latitude,longitude,population,perc_pop_world_share,perc_coverage,year
0,AD,Andorra,Europe,42.546245,1.601554,77072,0.00,0,1980
1,AD,Andorra,Europe,42.546245,1.601554,77072,0.00,0,1981
2,AD,Andorra,Europe,42.546245,1.601554,77072,0.00,0,1982
3,AD,Andorra,Europe,42.546245,1.601554,77072,0.00,0,1983
4,AD,Andorra,Europe,42.546245,1.601554,77072,0.00,0,1984

In [33]:
# Make a small data frame out of the bigger one to use all the columns I need for analysis
subset = country_coverage_info[["name","continent","year","population","perc_coverage",
                                "perc_pop_world_share"]]

subset.head()

      name continent  year  population perc_coverage perc_pop_world_share
0  Andorra    Europe  1980       77072             0                 0.00
1  Andorra    Europe  1981       77072             0                 0.00
2  Andorra    Europe  1982       77072             0                 0.00
3  Andorra    Europe  1983       77072             0                 0.00
4  Andorra    Europe  1984       77072             0                 0.00

In [34]:
# Converting columns with  
subset["perc_pop_world_share"] = pd.to_numeric(subset["perc_pop_world_share"])
subset["year"] = pd.to_numeric(subset["year"])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

### After running the above code to convert all the columns that have integer values into type int or float I learnt that some of the column values for the perc_coverage column were integers written like '52 52' when infact they meant 52. All of these values were for Nauru. Unless this data is not cleaned up. I can not proceed with analyzing this data
#### HOW TO FIX THIS:
###### Initial idea was to get all the issues into a string and then split it and use the .replace  but I was hard coding the location of in the table where this issue was. 
###### Decided instead to loop over the whole column of the table and fix anywhere the issues were the same

In [35]:
subset["perc_coverage"] = pd.to_numeric(subset["perc_coverage"])

ValueError: Unable to parse string "52 52" at position 4260

In [36]:
# This shows that the new data types of the columns we chaged 
subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6156 entries, 0 to 6155
Data columns (total 6 columns):
name                    6156 non-null object
continent               6156 non-null object
year                    6156 non-null int64
population              6156 non-null int64
perc_coverage           6156 non-null object
perc_pop_world_share    6156 non-null float64
dtypes: float64(1), int64(2), object(3)
memory usage: 288.6+ KB

In [37]:
# list_for_nauru=[]
# list_a=[]

# for i in range(4260,4293):
#     x = subset.loc[i,"perc_coverage"]
#     list_for_nauru.append(x)

# for a in range(len(list_for_nauru)):
#     q = list_for_nauru[a].split(" ")[0]
#     list_a.append(q)
# list_a
    
# #     for a in range(len(list_for_nauru)):
# #         subset['perc_coverage'] = subset['perc_coverage'].replace([list_for_nauru[a]], '52')

In [38]:
# for i in range(4260,4293):
#     x = subset.loc[i,"perc_coverage"]
#     q = x.split(" ")[0]
#     subset.loc[i,"perc_coverage"]= q

In [39]:
perc_coverage = subset["perc_coverage"]

for i in range(len(perc_coverage)):
    
    if isinstance(perc_coverage[i],str) and ' ' in perc_coverage[i]: 
        x = subset.loc[i,"perc_coverage"] 
        q = x.split(" ")[0]
        subset.loc[i,"perc_coverage"]= q
    else:
        pass

/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [40]:
subset["perc_coverage"] = pd.to_numeric(subset["perc_coverage"])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [41]:
subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6156 entries, 0 to 6155
Data columns (total 6 columns):
name                    6156 non-null object
continent               6156 non-null object
year                    6156 non-null int64
population              6156 non-null int64
perc_coverage           6156 non-null int64
perc_pop_world_share    6156 non-null float64
dtypes: float64(1), int64(3), object(2)
memory usage: 288.6+ KB

In [42]:
subset.head()

      name continent  year  population  perc_coverage  perc_pop_world_share
0  Andorra    Europe  1980       77072              0                   0.0
1  Andorra    Europe  1981       77072              0                   0.0
2  Andorra    Europe  1982       77072              0                   0.0
3  Andorra    Europe  1983       77072              0                   0.0
4  Andorra    Europe  1984       77072              0                   0.0

In [44]:
subset.to_excel("cleaned_data.xlsx")